In [30]:
from Data import *
from NeuralNetwork import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [31]:
(train_images, train_labels), (test_images, test_labels)   =  load_data(name = 'fashion_mnist')
train_images, train_labels, valid_images, valid_labels = split_validation(train_images, train_labels, valid_size=0.1, seed = 42)
train_images, train_labels,_,_ = split_validation(train_images, train_labels, valid_size=0.95, seed = 42)
X_train, X_valid, X_test = preprocess(train_images), preprocess(valid_images), preprocess(test_images)
y_train, y_valid, y_test = one_hot_encoded(train_labels), one_hot_encoded(valid_labels), one_hot_encoded(test_labels)


In [37]:

#Reading the config file

#Getting the configutation from wandb sweep
num_layers = 4
hidden_size = 128
lr = 1e-4
beta = 0.9
beta_m = 0.9
beta_v = 0.99
alpha = 5e-4
winit = "Xavier"
bs = 16
epochs = 10
optimizer_name = 'sgd'
g_activation = "tanh"


#Preparing hyperparameters for our optimizer
if optimizer_name == 'sgd':
    optim_hp = {'learning_rate':lr, 'alpha': alpha}
elif optimizer_name == 'momentum' or optimizer_name == 'nag' or optimizer_name == 'rmsprop':
    optim_hp = {'learning_rate':lr, 'beta': beta, 'alpha': alpha}
elif optimizer_name == 'adam' or optimizer_name == 'nadam':
    optim_hp = {'learning_rate':lr, 'beta_m': beta_m, 'beta_v': beta_v, 'alpha':alpha}

n_features = X_train.shape[1]
n_classes = y_train.shape[1]
hidden_sizes = [hidden_size]*num_layers + [n_classes]

network_hp = {'batch_size': bs, 'g_activation': ACTIVATIONS_MAP[g_activation]}
mynn = MyNeuralNetwork(n_features, hidden_sizes, n_classes)
mynn.update_network_hp(**network_hp)  
mynn.update_optim_hp(optimizer_name,**optim_hp)   
mynn.params_init(way = winit) 
mynn.train(X_train,y_train,X_valid,y_valid,epochs = epochs)

Epoch 0, T_Loss: 2.305275389600528, T_acc: 0.1262962962962963, V_Loss: 2.30594454474325, V_acc: 0.1255
Epoch 1, T_Loss: 2.0440304734267096, T_acc: 0.24925925925925926, V_Loss: 2.046231431617128, V_acc: 0.2445
Epoch 2, T_Loss: 1.84384617267119, T_acc: 0.3207407407407407, V_Loss: 1.8479707901845268, V_acc: 0.3268333333333333
Epoch 3, T_Loss: 1.6824995166377021, T_acc: 0.3488888888888889, V_Loss: 1.6870452481188634, V_acc: 0.357
Epoch 4, T_Loss: 1.5557881459365204, T_acc: 0.3814814814814815, V_Loss: 1.5606155838075577, V_acc: 0.383
Epoch 5, T_Loss: 1.4518087782674538, T_acc: 0.4085185185185185, V_Loss: 1.4574649084179914, V_acc: 0.4086666666666667
Epoch 6, T_Loss: 1.3668714827712847, T_acc: 0.43074074074074076, V_Loss: 1.3736972963975138, V_acc: 0.43116666666666664
Epoch 7, T_Loss: 1.298525707271811, T_acc: 0.4659259259259259, V_Loss: 1.3065707162540923, V_acc: 0.46416666666666667
Epoch 8, T_Loss: 1.2436455889341242, T_acc: 0.5048148148148148, V_Loss: 1.2527518022850452, V_acc: 0.49316666

In [33]:
mynn.weights[0]

array([[ 0.01772481, -0.00493384,  0.0231122 , ..., -0.04765059,
         0.01356703,  0.02178821],
       [ 0.01997563,  0.03856671,  0.03093526, ..., -0.0090684 ,
         0.0023905 ,  0.01841084],
       [-0.05575807, -0.01887878,  0.02834232, ..., -0.01398888,
         0.0378229 ,  0.02201731],
       ...,
       [ 0.0319868 ,  0.02673735, -0.01335117, ...,  0.02254338,
        -0.02667839,  0.04674911],
       [-0.02085302,  0.03958946,  0.08083221, ...,  0.02941196,
         0.00889504, -0.00427238],
       [ 0.00222479,  0.00266294,  0.04193468, ..., -0.02031125,
         0.05703667, -0.02343359]])

In [25]:
mynn.train(X_train,y_train,X_valid,y_valid,epochs = 10)

Epoch 0, T_Loss: 1.859315632527439, T_acc: 0.23592592592592593, V_Loss: 1.8575566741113119, V_acc: 0.23866666666666667
Epoch 1, T_Loss: 1.9175079987000518, T_acc: 0.22148148148148147, V_Loss: 1.934515260370076, V_acc: 0.21166666666666667
Epoch 2, T_Loss: 1.9771581499629145, T_acc: 0.22111111111111112, V_Loss: 2.0008885753759165, V_acc: 0.21216666666666667
Epoch 3, T_Loss: 1.7317235633765997, T_acc: 0.26407407407407407, V_Loss: 1.742943337378979, V_acc: 0.26316666666666666
Epoch 4, T_Loss: 1.7741181627893656, T_acc: 0.24259259259259258, V_Loss: 1.7785471558641266, V_acc: 0.24266666666666667
Epoch 5, T_Loss: 1.628909223227189, T_acc: 0.2833333333333333, V_Loss: 1.639248265080958, V_acc: 0.281
Epoch 6, T_Loss: 1.8459224000637853, T_acc: 0.20074074074074075, V_Loss: 1.8469254544967248, V_acc: 0.201
Epoch 7, T_Loss: 2.1595353996247275, T_acc: 0.2788888888888889, V_Loss: 2.173633069145296, V_acc: 0.27366666666666667
Epoch 8, T_Loss: 2.224629325845141, T_acc: 0.17222222222222222, V_Loss: 2.26

In [ ]:
y_test_pred = mynn.predict(X_test)

In [ ]:
print(np.sum(np.argmax(y_test,axis = 1)==np.argmax(y_test_pred,axis = 1))/y_test.shape[0])

0.7294


In [ ]:
from collections import Counter
np.unique(np.argmax(y_train,axis = 1), return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([270, 270, 270, 270, 270, 270, 270, 270, 270, 270]))

In [ ]:
mynn.weights[0]

array([[ 0.44397905, -0.2270532 ,  0.85351622, ..., -1.66284238,
         0.06621643,  0.46687932],
       [ 0.55918849,  1.16691805,  0.87170058, ..., -0.33291553,
         0.1899259 ,  0.71354788],
       [-1.5601007 , -0.5778982 ,  0.67630795, ..., -0.57130518,
         0.88317859,  0.44534818],
       ...,
       [-0.53291019, -0.67599409,  1.37280076, ...,  1.81105739,
        -0.12194865,  0.84618229],
       [ 0.82133766,  0.64010845, -0.43371267, ..., -1.92825264,
        -0.22334057, -0.67335536],
       [ 1.76370395, -0.02307934, -0.35251759, ...,  1.24726423,
         1.64829953,  1.31408006]])